// Svelte bindings for xray

export type {
  AssertionResult,
  ConsoleEntry,
  DomQueryResult,
  FocusInfo,
  NetworkRequest,
  PerformanceMetrics,
  RegisteredState,
  StorageInfo,
  ViewportInfo,
  XrayAction,
  XrayCollector,
  XrayConfig,
  XrayError,
  XrayFunction,
  XrayScope,
  XrayState,
} from '@deepnoodle/xray-core'

// Re-export core types and utilities for convenience
export {
  captureScreenshot,
  clickElement,
  createCollector,
  createXrayScope,
  executeAction,
  executeFunction,
  fillInput,
  getAccessibilityInfo,
  getActions,
  getCollector,
  getFocusInfo,
  getFunctions,
  getPerformanceMetrics,
  getStorageInfo,
  getViewportInfo,
  goBack,
  goForward,
  navigate,
  queryDom,
  refresh,
  registerAction,
  registerFunction,
  scrollTo,
  setCollector,
  setupInterceptors,
  unregisterAction,
  unregisterFunction,
} from '@deepnoodle/xray-core'
export {
  createXrayScopeWithCleanup,
  getXrayCollector,
  initXray,
  registerState,
  registerXrayAction,
  registerXrayFunction,
  trackStore,
  unregisterState,
  type XrayOptions,
} from './store.js'
