// Vue bindings for xray

export type {
  AssertionResult,
  ConsoleEntry,
  DomQueryResult,
  FocusInfo,
  NetworkRequest,
  PerformanceMetrics,
  RegisteredState,
  StorageInfo,
  ViewportInfo,
  XrayAction,
  XrayCollector,
  XrayConfig,
  XrayError,
  XrayFunction,
  XrayScope,
  XrayState,
} from 'xray-core'
// Re-export core types and utilities for convenience
export {
  captureScreenshot,
  clickElement,
  createCollector,
  createXrayScope,
  executeAction,
  executeFunction,
  fillInput,
  getAccessibilityInfo,
  getActions,
  getCollector,
  getFocusInfo,
  getFunctions,
  getPerformanceMetrics,
  getStorageInfo,
  getViewportInfo,
  goBack,
  goForward,
  navigate,
  queryDom,
  refresh,
  registerAction,
  registerFunction,
  scrollTo,
  setCollector,
  setupInterceptors,
  unregisterAction,
  unregisterFunction,
} from 'xray-core'
export {
  useXray,
  useXrayAction,
  useXrayCollector,
  useXrayCustom,
  useXrayFunction,
  useXrayScope,
} from './composables.js'
export {
  cleanupXray,
  getXrayCollector,
  type XrayPluginOptions,
  xrayVuePlugin,
  xrayVuePlugin as default,
} from './plugin.js'
